### ISSUE TITLE
Do not use == for signature verification

### ISSUE THREAD

**Issue by singpolyma** [vincenthz/hs-crypto-cipher#10]
Because of timing attacks.  Use http://hackage.haskell.org/packages/archive/crypto-api/0.10.1/doc/html/Crypto-Classes.html#v:constTimeEq instead

**Comment by vincenthz** [comment]
This is a _public_ signature with a _public_ key: anyone can verify that the values are identical, so i'm not sure i can imagine any timing attacks here. any scenario where that would make sense ?

**Comment by singpolyma** [comment]
If the library is being used with any of the values not published (ie, keys internal to the application) it could be a problem.  It might not be in most uses of signatures (like email), but since this is a generic library we cannot predict uses users might have for it, and the fix is super easy, so I propose that it's useful as a guard against that one guy who uses RSA signatures in what may seem a less-than-conventional way.

**Comment by vincenthz** [comment]
Even then, the hash of the message is known and the tag is going through a expmod with an _unknown_ modulo (public key internal to application). As to forging your signature using a timing attack, i don't see how you could tweak the signature as to benefit from knowing how many bytes are matching: this is not a linear (or guessable) progression because of the unknown expmod. Which means this is still pretty much a brute force attack.

**Comment by singpolyma** [comment]
You're probably right.  This just seemed like a simple change to me on the angle of "make fewer assumptions."

But it's possible that no reasonable use of the library makes this a problem.

**Comment by TomMD** [comment]
And crypto-api inclues the constTimeEq these days!

**Comment by vincenthz** [comment]
I think that putting a const eq here will give a false sense of security as there's no need for it. And, there's other part of the implementation that looks more worrying TBH.

Also, i had a quick look into gnutls (gcrypt) and openssl implementation of rsa verify; as I suspected, none of them compare with a constant eq.
