### ISSUE TITLE
uint8_t /= _m128i

### ISSUE THREAD

**Issue by TomMD** [vincenthz/hs-crypto-cipher#13]
Am I nuts or are you using a structure for expanded AES keys that is 20 bytes large and storing 320 bytes in it?

**Comment by vincenthz** [comment]
Looks like something got lost in the aes.h file. there use to be a multiplcation that does 16_AES128_NB_ROUNDS_2 instead of "20".

Practically though it doesn't matter as this value is not used, the allocation is purely done (correctly) and 16-aligned at the haskell level. Maybe i should just replace it by a uint8_t pointer so that it doesn't confuse people :-)

**Comment by TomMD** [comment]
I think having the size of the structure correct in C would be better than a sizeless pointer.  I hope to release an RNG using a trampoline between your code and Gladman's via a runtime check and aided by a compile time (cabal-custom Setup.hs) check for the right intrinsics headers.
