### ISSUE TITLE
AES module is empty in 0.4.0

### ISSUE THREAD

**Issue by Magicloud** [vincenthz/hs-crypto-cipher#24]
The document is empty.
The modules use AES cannot be compiled.

**Comment by vincenthz** [comment]
it seems to be just a haddock problem (either bug or by design dunno). maybe it's linked with the PackageImport extension ? according to the documentation (http://www.haskell.org/haddock/doc/html/ch03s04.html#id565339) it should re-export the whole documentation.

The AES code seems to work otherwise.
You can refer to the documentation in cipher-aes for now http://hackage.haskell.org/package/cipher-aes for now.

**Comment by vincenthz** [comment]
closed now that cryptocipher just export cipher types and generics classes

**Comment by Magicloud** [comment]
Sorry, forgot to answer to this. It has been solved for long. Thank you.
